### ISSUE TITLE
Multilingual Edition of Edition

### ISSUE THREAD

**Issue by jhabdas** [CloudCannon/edition-jekyll-template#3]
I forked this wonderful template for use documenting the [Hyperdrive Plugin for WordPress](https://github.com/wp-id/hyperdrive). I'm currently working on Internationalization as our documentation will be translated into multiple languages. Thoughts on incorporating i18n/L10n into the base template?

**Comment by mneumegen** [comment]
The multilingual plugins we've looked at so far all have limitations. We're looking to build something later this year to address this.
